env: tictactoe
agent: expert_apprentice
opponent: random
agent_params:
  lr: 0.001
  hidden_layers: [16, 16]
  mlp_activation: relu
  n_simulations: 120
  c_uct: 1.41
  max_rollout_depth: 200
  gamma: 1.0
  buffer_capacity: 100000
  batch_size: 128
  learning_starts: 4000
  train_steps_per_observe: 2
training:
  num_episodes: 50000
  max_steps_per_episode: 200
eval:
  checkpoints:
    - 1000
    - 10000
    - 50000
  num_games: 100
seeds:
  - 1
  - 2
