env: bobail
agent: reinforce_critic
opponent: random

agent_params:
  lr: 0.0005
  critic_lr: 0.0005
  gamma: 0.99
  hidden_layers: [256, 128]

training:
  num_episodes: 100000
  max_steps_per_episode: 500

eval:
  checkpoints: [1000, 2000, 4000, 5000, 10000, 20000, 40000, 50000, 100000]
  num_games: 50

seeds: [42, 123]
